---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: scrathpad
  namespace: "user-ns-unison-test-user-3"
  labels:
    app: scrathpad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrathpad
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scrathpad
    spec:
      containers:
        - name: bsidesnovascratchpad
          image: docker.io/mlbiam/bsidesnovascratchpad:signed
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600